# -*- coding: utf-8 -*-
"""
Sentinel-Scraper - 官方核心政策与宏观调控情报源（100个）
聚焦：国家部委、行业监管、地方招投标、A/H/美股市场大本营
"""

OFFICIAL_SOURCES = {
    # ==================== 一、宏观经济与资本市场监管（核心风向标） ====================
    "中国政府网-国务院政策": "https://www.gov.cn/zhengce/",
    "国家发改委-政策发布": "https://www.ndrc.gov.cn/xxgk/zcfb/",
    "中国人民银行-公开市场操作": "https://www.pbc.gov.cn/goutongjiaoliu/113456/113469/index.html",
    "中国证监会-政策法规": "https://www.csrc.gov.cn/csrc/c101918/zfxxgk_zdgk.shtml",
    "国家外汇管理局-政策法规": "https://www.safe.gov.cn/safe/zcfg/index.html",
    "财政部-税政司": "https://szs.mof.gov.cn/zhengcefabu/",
    "国家统计局-最新发布": "https://www.stats.gov.cn/sj/zxfb/",
    "国家金融监督管理总局-政策法规": "https://www.cbirc.gov.cn/cn/view/pages/ItemList.html?itemcode=921",
    "中国银行间市场交易商协会-自律管理": "https://www.nafmii.org.cn/zlygl/",
    "国资委-政策文件": "https://www.sasac.gov.cn/n2588035/n2588320/index.html",
    # ==================== 二、对外贸易、关税与地缘供应链博弈 ====================
    "中华人民共和国商务部-外贸管理": "https://wms.mofcom.gov.cn/zcfb/wmgl/index.html",
    "商务部-贸易救济调查局(反倾销调查)": "https://trb.mofcom.gov.cn/article/cx/",
    "商务部-安全管制局(出口管制)": "https://aqgzj.mofcom.gov.cn/article/zcfb/",
    "海关总署-政策法规公告": "https://www.customs.gov.cn/customs/302249/302266/index.html",
    "海关总署-月度进出口商品量值表": "https://www.customs.gov.cn/customs/302249/zfxxgk/2799825/302274/302277/index.html",
    "中国贸促会-海外经贸摩擦预警": "https://www.ccpit.org/yjjw/",
    "国家移民管理局-出入境政策": "https://www.nia.gov.cn/n741440/n741542/index.html",
    "商务部-美大司(对美贸易追踪)": "https://mds.mofcom.gov.cn/article/g/",
    "商务部-条法司(国际WTO贸易争端)": "https://tfs.mofcom.gov.cn/article/y/",
    "世界贸易组织-中国贸易政策审议": "https://www.wto.org/english/tratop_e/tpr_e/tpr_e.htm",
    # ==================== 三、工业金属、资源、能源与大宗商品 ====================
    "自然资源部-矿业权出让公示": "https://www.mnr.gov.cn/dt/yw/kyq/",
    "国家能源局-政策法规公告": "https://nea.gov.cn/zdgk/zcfg/",
    "工业和信息化部-原材料工业(钢铁/稀土/有色)": "https://www.miit.gov.cn/gxsj/yclgy/",
    "中国有色金属工业协会-行业要闻": "https://www.cnfa.org.cn/hangyeyaowen/",
    "中国稀土行业协会-数据公告": "https://www.crea.org.cn/index/index/lists/catid/4.html",
    "中国黄金协会-行业动态": "https://www.china-gold.org.cn/news/industry/",
    "中国煤炭工业协会-运行分析": "https://www.coalchina.org.cn/index.php?m=content&c=index&a=lists&catid=14",
    "生态环境部-全国碳排放交易动态": "https://www.mee.gov.cn/ywgz/ydqhbh/wrypfqkzl/",
    "国家粮食和物资储备局-公开信息": "https://www.lswz.gov.cn/html/gk/index.html",
    "上海期货交易所-新闻公告": "https://www.shfe.com.cn/news/notice/",
    # ==================== 四、半导体、硬科技与高端制造 ====================
    "工信部-电子信息司(半导体/集成电路)": "https://www.miit.gov.cn/gxsj/dzxx/",
    "国家知识产权局-专利审查公告": "https://shuju.cnipa.gov.cn/home",
    "科技部-国家高新技术动态": "https://www.most.gov.cn/kjbgz/",
    "工信部-装备工业司(机器人/数控机床)": "https://www.miit.gov.cn/gxsj/zbgy/",
    "国家国防科技工业局-军工军品管理": "https://www.sastind.gov.cn/n6759534/n6759547/index.html",
    "全军武器装备采购信息网-采购公告(军工风向标)": "https://www.weain.mil.cn/cggg/zbcg/",
    "中国半导体行业协会-产业资讯": "https://www.csia.net.cn/Article/ShowClass.asp?ClassID=2",
    "工信部-安全生产司(民爆/工业气体安全控制)": "https://www.miit.gov.cn/gxsj/aqsc/",
    "中国化学品安全协会-政策法规": "https://www.chemicalsafety.org.cn/laws/laws_list",
    "国家航天局-重大项目推进": "https://www.cnsa.gov.cn/n6758822/n6758838/index.html",
    # ==================== 五、医药生物、医疗器械与化学制药 ====================
    "国家药品监督管理局-最新公告": "https://www.nmpa.gov.cn/xxgk/ggtg/index.html",
    "国家药监局-药品审评中心(CDE受理公示)": "https://www.cde.org.cn/main/xxgk/listpage/1c180903b41e3d48956e187766b96e17",
    "国家医保局-医保目录与集采动态": "https://www.nhsa.gov.cn/col/col18/index.html",
    "国家卫生健康委-体制改革与政策": "https://www.nhc.gov.cn/tgs/index.shtml",
    "中国食品药品检定研究院-通知公告": "https://www.nifdc.org.cn/nifdc/bwcx/tzgg/index.html",
    "上海阳光医药采购网-国家集采专栏": "https://www.smpaa.cn/gjsmdjbg/index.shtml",
    "国家药监局-医疗器械审评中心": "https://www.cmde.org.cn/xwdt/clgg/index.html",
    "中国生物工程学会-前沿动态": "https://www.biotech.org.cn/news_list.html",
    "农业农村部-基因改性与生物育种管理": "https://www.moa.gov.cn/ztzl/zmgmo/zcfg/",
    "国家中医药管理局-政策法规": "https://www.satcm.gov.cn/xxfb/zcfg/",
    # ==================== 六、汽车、新能源、锂电与光伏储能 ====================
    "工信部-道路机动车辆生产企业及产品准入公告": "https://www.miit.gov.cn/gxsj/clgy/",
    "国家发改委-高技术产业司(新能源投资)": "https://www.ndrc.gov.cn/xxgk/jd/gjscyj/",
    "中国汽车工业协会-产销数据发布": "https://www.caam.org.cn/chn/4/cate_27/list_1.html",
    "中国乘用车联席会(乘联会)-市场分析": "http://www.cpcaauto.com/news.php?types=scfx",
    "生态环境部-大气环境司(机动车排放标准)": "https://www.mee.gov.cn/ywgz/dqhjbh/jdcwrypfgl/",
    "中国光伏行业协会-市场动态": "https://www.cpvia.org.cn/news/3.html",
    "中国化学与物理电源行业协会-锂电/储能数据": "https://www.ciaps.org.cn/news/list?cid=10",
    "交通运输部-新能源物流车推进": "https://xxgk.mot.gov.cn/2020/jigou/ysfws/index.html",
    "住房和城乡建设部-充电基础设施建设规划": "https://www.mohurd.gov.cn/gongkai/fdzdgknr/index.html",
    "国家标准化管理委员会-新能源汽车标准": "https://www.sac.gov.cn/tzgg/",
    # ==================== 七、数字经济、人工智能、大模型与算力基础设施 ====================
    "国家数据局-政策发布": "https://www.ndrc.gov.cn/xxgk/zcfb/gjjg/",
    "中央网信办-生成式人工智能/大模型备案公示": "https://www.cac.gov.cn/ycwxb/index.html",
    "工信部-信息通信管理局(5G/算力网络)": "https://www.miit.gov.cn/gxsj/txgl/",
    "国家广播电视总局-网络视听管理": "https://www.nrta.gov.cn/col/col113/index.html",
    "中国信息通信研究院(信通院)-白皮书发布": "https://www.caict.ac.cn/kxyj/qwfb/bps/",
    "工信部-网络安全管理局": "https://www.miit.gov.cn/gxsj/wlan/",
    "科技部-人工智能重大专项": "https://www.most.gov.cn/ztzl/zgzlgjhjs/",
    "国家密码管理局-商用密码标准": "https://www.sca.gov.cn/sca/zcfg/toc_list.shtml",
    "中国互联网络信息中心(CNNIC)-统计报告": "https://www.cnnic.net.cn/n4/2024/0322/c101-11103.html",
    "交通运输部-自动驾驶准入试点": "https://xxgk.mot.gov.cn/2020/jigou/yjys/",
    # ==================== 八、房地产、地方化债与基础设施投资 ====================
    "住房和城乡建设部-房地产市场政策": "https://www.mohurd.gov.cn/gongkai/fdzdgknr/zfhcxjsbwj/index.html",
    "财政部-地方政府债券发行统计": "https://gks.mof.gov.cn/tongjishuju/",
    "中国人民银行-金融市场司(房贷利率底线)": "https://www.pbc.gov.cn/jinrongshichangsi/146816/index.html",
    "国家发改委-固定资产投资项目审批": "https://www.ndrc.gov.cn/xxgk/zcfb/tz/",
    "交通运输部-公路水路固定资产投资": "https://xxgk.mot.gov.cn/2020/gongkai/tongjishuju/",
    "国家铁路局-铁路建设规划动态": "https://www.nra.gov.cn/xxgk/ggl/index.html",
    "水利部-水利基础设施建设推进": "https://www.mws.gov.cn/gongkai/fdzdgknr/tzgg/",
    "中国建筑业协会-行业统计": "https://www.zgjzy.org.cn/html/tjxx/index.html",
    "中国房地产业协会-行业动态": "https://www.fangchan.org.cn/news/index.html",
    "自然资源部-住宅用地出让公告": "https://www.mnr.gov.cn/dt/yw/td/",
    # ==================== 九、三大交易所与中介监管（A股/H股二级市场大本营） ====================
    "上海证券交易所-最新公告": "https://www.sse.com.cn/aboutus/mediacenter/hotandnotice/sscgg/",
    "深圳证券交易所-信息披露公告": "https://www.szse.cn/disclosure/notice/index.html",
    "北京证券交易所-重要公告": "https://www.bse.cn/important_news.html",
    "香港交易所(HKEX)-新闻中心": "https://www.hkex.com.cn/News/Market-Release?sc_lang=zh-CN",
    "中国证券业协会-自律惩戒公告": "https://www.sac.net.cn/hymsh/zlcl/",
    "中国证券投资基金业协会-私募登记备案公示": "https://www.amac.org.cn/businessservices/amf/公示信息/",
    "中证金融公司-转融通业务数据": "https://www.csf.com.cn/cms/channels/450.html",
    "中央结算公司-债券市场发行公告": "https://www.chinabond.com.cn/cb/cn/xwgg/gg/",
    "中国证券登记结算公司-开户数据": "https://www.chinaclear.cn/zdjs/editor_bgt/list_shuju.shtml",
    "审计署-国有企业审计公告": "https://www.audit.gov.cn/n4/n19/index.html",
    # ==================== 十、重点区域、地方招投标与情报深挖 ====================
    "北京市发改委-重点项目批复": "https://fgw.beijing.gov.cn/bjfgw/gongkai/zcfb/index.html",
    "上海市发改委-政策文件": "https://fgw.sh.gov.cn/fgw_zcfg/index.html",
    "广东省发改委-通知公告": "https://drc.gd.gov.cn/ywtz/index.html",
    "深圳市发改委-重大项目进展": "https://fgw.sz.gov.cn/xxgk/qt/tzgg/",
    "雄安新区管委会-建设发展公告": "https://www.xiongan.gov.cn/xatg/",
    "中国政府采购网-中央采购公告": "https://www.ccgp.gov.cn/zycg/",
    "中国招标投标公共服务平台-全国招标信息": "https://bulletin.cebpubservice.com/",
    "国家电网采购采购网-招标公告": "https://ecp.sgcc.com.cn/ecp2.0/portal/#/list-notice-bulletin",
    "中国石油招标投标网-中标公示": "https://ebid.cnpc.com.cn/bidHome/index.html",
    "中国石化电子招标投标交易平台": "https://ebidding.sinopec.com/v1/pms/index.html",
}
