# -*- coding: utf-8 -*-
"""
Sentinel-Scraper - 市场情绪、海外博弈与全球突发热点情报源（100个）
聚焦：地缘博弈、美股科技巨头（英伟达/特朗普/降息）、大宗商品异动与科技内幕
"""

TRENDING_SOURCES = {
    # ==================== 一、全球地缘政治、宏观博弈与突发事件（特朗普、制裁、关税） ====================
    "路透社-全球地缘与宏观头条": "https://www.reuters.com/world/",
    "彭博社-全球宏观经济与政策": "https://www.bloomberg.com/economics",
    "CNBC-政治与白宫动态": "https://www.cnbc.com/politics/",
    "联合早报-中国与全球地缘政经": "https://www.zaobao.com/realtime/china",
    "金融时报-国际政治博弈(FT)": "https://www.ft.com/world",
    "华尔街日报-海外地缘要闻": "https://www.wsj.com/news/world",
    "Politico-美国政策与白宫动向专栏": "https://www.politico.com/",
    "外交政策(Foreign Policy)-全球博弈专栏": "https://foreignpolicy.com/",
    "新华网-国际热点突发": "http://www.news.cn/world/index.html",
    "参考消息-海外看中国与突发冲突": "http://www.cankaoxiaoxi.com/world/",
    # ==================== 二、美股科技巨头、半导体与AI前沿（英伟达、AMD、ASML、美光） ====================
    "TechCrunch-全球硬科技爆料": "https://techcrunch.com/",
    "The Verge-AI与硅谷巨头动态": "https://www.theverge.com/ai-artificial-intelligence",
    "Tom's Hardware-半导体硬件与供应链情报": "https://www.tomshardware.com/",
    "Wccftech-英伟达/AMD与芯片产业前沿线报": "https://wccftech.com/category/chips/",
    "Semiconductor Engineering-半导体工程与工艺突发": "https://semiengineering.com/",
    "集邦咨询(TrendForce)-全球半导体与存储报价": "https://www.trendforce.cn/news/",
    "DIGITIMES-电子时报(半导体晶圆代工线报)": "https://www.digitimes.com.cn/",
    "芯智讯-国内半导体与海外制裁拆解": "https://www.icsmart.cn/",
    "集微网-集成电路与硬科技独家内幕": "https://www.laoyaoba.com/",
    "半导体行业观察-全球芯片供应链研究": "http://www.semiinsights.com/",
    # ==================== 三、A股/美股实时高频情绪风向标（雪球爆款、股吧异动、热搜） ====================
    "东方财富网-热门话题": "https://gubatopic.eastmoney.com/",
    "雪球网-今日热门讨论榜": "https://xueqiu.com/today",
    "新浪财经-7x24小时全球直播流": "https://finance.sina.com.cn/7x24/",
    "华尔街见闻-实时全球大事件快讯": "https://wallstreetcn.com/live/global",
    "财联社-电报(主力资金与政策突发极其迅速)": "https://www.cls.cn/telegraph",
    "同花顺-财经热点要闻": "http://news.10ths.com.cn/",
    "证券时报-网易专栏(游资动向与题材炒作)": "https://news.secutimes.com/",
    "智通财经-港股/美股高频异动内幕": "https://www.zhitongcaijing.com/",
    "金十数据-全球央行与商品实时快讯": "https://www.jin10.com/",
    "百度财经热搜榜-大众情绪爆发点": "https://top.baidu.com/board?tab=finance",
    # ==================== 四、大宗商品、工业金属与工业气体突发异动（铜、铝、稀有气体、锂） ====================
    "伦敦金属交易所(LME)-全球有色金属高频新闻": "https://www.lme.com/en/News",
    "上海有色网(SMM)-铜铝价格与突发停产复产": "https://www.smm.cn/",
    "我的钢铁网(Mysteel)-有色/稀土供应链内幕": "https://youse.mysteel.com/",
    "Oilprice-全球原油与能源安全风向": "https://oilprice.com/",
    "百川盈孚-大宗商品与工业气体高频周报": "http://www.baiinfo.com/",
    "卓创资讯-化工与工业原料异动要闻": "https://www.sci99.com/",
    "阿格斯(Argus)-全球能源与稀有金属地缘报价": "https://www.argusmedia.com/zh-cn",
    "Fastmarkets-全球战略金属与半导体原材料研究": "https://www.fastmarkets.com/",
    "电池网-锂电、固态电池与钴锂资源风向": "http://www.itdcw.com/",
    "中国有色网-大宗商品行业风向": "http://www.cnmn.com.cn/",
    # ==================== 五、海外核心财经评论与聪明钱动向（大空头、华尔街投行、Reddit） ====================
    "Seeking Alpha-美股多空博弈深度辩论": "https://seekingalpha.com/",
    "ZeroHedge-关注地缘危机与系统性风险的宏观博客": "https://www.zerohedge.com/",
    "Motley Fool-美股热门个股逻辑拆解": "https://www.fool.com/",
    "Reddit-r/wallstreetbets (美股情绪大本营)": "https://www.reddit.com/r/wallstreetbets/",
    "Reddit-r/stocks (美股核心价值投资讨论区)": "https://www.reddit.com/r/stocks/",
    "MarketWatch-美股突发热点与异动股追踪": "https://www.marketwatch.com/",
    "Business Insider-商业内幕与硅谷大佬动态": "https://www.businessinsider.com/",
    "巴伦周刊-全球资本市场核心投资逻辑": "https://www.barrons.com/",
    "Investor's Business Daily-美股放量突破追踪": "https://www.investors.com/",
    "高盛(Goldman Sachs)-全球宏观研究公开发布": "https://www.goldmansachs.com/insights/",
    # ==================== 六、AI大模型、商业落地与算力基建爆料（OpenAI, Anthropic） ====================
    "AI News-全球大模型产业应用线报": "https://www.artificialintelligence-news.com/",
    "Hugging Face-开源大模型与技术趋势趋势榜": "https://huggingface.co/papers",
    "VentureBeat-AI与企业级算力中心建设异动": "https://venturebeat.com/category/ai/",
    "MIT Technology Review-麻省理工科技评论": "https://www.technologyreview.com/",
    "机器之心-国内最全的AI前沿与科技大厂内幕": "https://www.jiqizhixin.com/",
    "量子位-AI科技巨头与硬科技创业前沿风向": "https://www.liangziwei.net/",
    "新智元-AI/芯片/人形机器人产业爆发点": "https://www.syncedreview.com/",
    "钛媒体-TMT科技与资本运作爆料": "https://www.tmtpost.com/",
    "36氪-硬科技、出海与赛道高频融资线报": "https://36kr.com/information/technology",
    "虎嗅网-大科技公司战略调控与行业内幕批判": "https://www.huxiu.com/",
    # ==================== 七、中国制造、出海链与供应链突发（跨境电商、新三样） ====================
    "雨果跨境-中国制造出海政策与红利/风控": "https://www.cifnews.com/",
    "一财网-第一财经(长三角/珠三角工业供应链调研)": "https://www.yicai.com/",
    "财新网-经济与高端制造独家深度(硬核突发)": "https://www.caixin.com/",
    "经济观察网-产业基本面与国资运作线报": "http://www.eeo.com.cn/",
    "21世纪经济报道-A股题材炒作与公司暴雷追踪": "https://www.21jingji.com/",
    "界面新闻-工业、新能源汽车与消费异动": "https://www.jiemian.com/",
    "每日经济新闻-全球上市公司异动与公告拆解": "https://www.nbd.com.cn/",
    "格隆汇-全球视野下的A股/港股核心题材挖掘": "https://www.gelonghui.com/",
    "证券时报网-游资龙虎榜与题材风口深度解析": "https://www.stcn.com/",
    "中国证券网-中证报(监管维稳与国家队动向)": "https://www.cnstock.com/",
    # ==================== 八、生物制造、创新药与出海供应链（CXO、基因、FDA） ====================
    "Fierce Pharma-全球创新药与FDA审批突发内幕": "https://www.fiercepharma.com/",
    "BioSpace-全球生物医药与基因工程线报": "https://www.biospace.com/",
    "Endpoints News-华尔街看重的创新药临床爆料": "https://endpts.com/",
    "医药魔方-国内创新药临床/集采/BD出海流": "https://www.pharmcube.com/",
    "丁香园-生物医药与临床医学一线热点": "https://www.dxy.cn/",
    "动脉网-医疗健康、生物制造与前沿风向": "https://vcbeat.top/",
    "生辉-前沿生物科技与合成生物学爆料": "https://www.deeptechchina.com/",
    "医药经济报-国内医药基本面政策拆解": "http://www.yyjjb.com.cn/",
    "FDA大事件快讯-海外核心准入突破": "https://www.fda.gov/news-events",
    "欧洲药品管理局(EMA)-新药临床线报": "https://www.ema.europa.eu/en/news",
    # ==================== 九、全球中央银行与资金流动（美联储降息、非农、日央行） ====================
    "美联储(Federal Reserve)-FOMC声明与利率决议": "https://www.federalreserve.gov/newsevents.htm",
    "欧洲中央银行(ECB)-政策发布流": "https://www.ecb.europa.eu/press/html/index.en.html",
    "日本银行(BOJ)-货币政策与套利资金走向": "https://www.boj.or.kr/eng/main/main.do",
    "英格兰银行-海外宏观紧缩异动": "https://www.bankofengland.co.uk/news",
    "国际货币基金组织(IMF)-全球经济展望更新": "https://www.imf.org/en/News",
    "国际清算银行(BIS)-全球金融稳定线报": "https://www.bis.org/list/press_releases/index.htm",
    "CME美联储观察工具新闻流-高频降息概率": "https://www.cmegroup.com/",
    "FXStreet-全球外汇与商品高频热点": "https://www.fxstreet.com/",
    "DailyFX-全球宏观、黄金、原油异动技术面": "https://www.dailyfx.com/",
    "Investing.com-全球财经晴雨表(突发快讯组)": "https://www.investing.com/news/g00",
    # ==================== 十、新材料、工业母机、国防与供应链极限施压 ====================
    "Defense News-全球国防工业与地缘局施压": "https://www.defensenews.com/",
    "Janes-全球防务与战略供应链博弈线报": "https://www.janes.com/",
    "ASMI官网新闻-全球半导体设备装机情报": "https://www.asm.com/en/news",
    "东京电子(TEL)-日本半导体设备出口线报": "https://www.tel.com/news",
    "应用材料(AMAT)-美股半导体基建风向": "https://www.appliedmaterials.com/us/en/news.html",
    "东方财富-概念板块排行(捕捉主力拉升题材)": "https://quote.eastmoney.com/center/boardlist.html",
    "中汽协-新能源汽车供应链卡脖子线报": "http://www.caam.org.cn/",
    "路透社-大宗商品与国际供应链博弈专栏": "https://www.reuters.com/markets/commodities/",
    "Seeking Alpha-英伟达(NVDA)多空前沿追踪": "https://seekingalpha.com/symbol/NVDA",
    "Reddit-r/AMD_Stock (算力博弈高频讨论区)": "https://www.reddit.com/r/AMD_Stock/",
}
